### ISSUE TITLE
Engravings throwing errors on new patch.

### ISSUE THREAD

**Issue by Barleduq** [TekNoLogic/Engravings#11]
Are you intending to update this? If so, I can post the errors from Swatter here, or on wowinterface.com which is where I dl from. 

Every time my mouse goes over something that *might* be an item - not just in my bags, but say I have an item pulled to a taskbar and the mouse slides over that button on the way somewhere else - I get a swatter window popping up. I haven't copied the error yet, because I wanted to know if it is worthwhile or if you'd stopped coding addons. My username is Barleduq on WoWI.

**Comment by Barleduq** [comment]
Further info:  I did post errors on wowinterface.  When this addon is enabled, and throwing errors, it keeps Can I Mogit? and Altoholic from populating the tooltip, *and* apparently prevents the ability to compare gear in bags and gear worn by pressing the shift key.  o.O 

Please let me know if you are dropping your addons? I prefer the minimalist usefulness, so if you're going to continue them I'd rather wait.

**Comment by tekkub** [comment]
Updates are coming, but Engravings is going to need a bit of work.  You can grab the latest from this repo to fix a few of the more severe bugs, I'll have a proper update Soon™.

**Comment by Barleduq** [comment]
Forgive my ignorance, I'm not a coder and haven't used Github before. The most recent date I see on the Releases page is 2015 for the file 6.0.0.30-Beta, which is the same name as the file on wowinterface.com. Is that what I should download, from here?

**Comment by Talyrius** [comment]
Visit the [dataminer](https://github.com/TekNoLogic/Engravings/tree/dataminer) branch and click the 'Clone or download' button to get the ZIP file. When extracting, rename the 'Engravings-dataminer' directory to 'Engravings' or it won't load.

**Comment by tekkub** [comment]
Updates should be in the wild now.
