### ISSUE TITLE
Error when mousing over the engravings icon 

### ISSUE THREAD

**Issue by Barleduq** [TekNoLogic/Engravings#15]
I have the Engravings Icon collected into Norganna's Slidebar, which is included in the Auctioneer Suite set of addons.  I happened to open it up and ran my mouse over the line to get to antoher icon, and this popped up. 

Date: 2016-11-01 13:02:53
ID: 2
Error occured in: AddOn: Engravings
Count: 1
Message: Note: AddOn Engravings attempted to call a protected function (OverrideActionBarButton4:Show()) during combat lockdown.
Debug:
   [C]: Show()
   ..\FrameXML\ActionButton.lua:330: ActionButton_Update()
   ..\FrameXML\ActionButton.lua:665: ActionButton_OnEvent()
   ..\FrameXML\ActionButton.lua:174:
      ..\FrameXML\ActionButton.lua:171
Locals:
None
AddOns:
  Swatter, v7.2.5682 (TasmanianThylacine)
  ACP, v3.4.30 
  Altoholic, vr172
  Analyst, v1.4.0
  Archy, v7.1.0.1
  AucAdvanced, v7.2.5682 (TasmanianThylacine)
  AucFilterBasic, v7.2.5682 (TasmanianThylacine)
  AucFilterOutlier, v7.2.5682.5459(/embedded)
  AucMatchUndercut, v7.2.5682.5585(/embedded)
  AucScanData, v7.2.5682 (TasmanianThylacine)
  AucStatHistogram, v7.2.5682 (TasmanianThylacine)
  AucStatiLevel, v7.2.5682 (TasmanianThylacine)
  AucStatPurchased, v7.2.5682 (TasmanianThylacine)
  AucStatSales, v7.2.5682.5598(/embedded)
  AucStatSimple, v7.2.5682 (TasmanianThylacine)
  AucStatStdDev, v7.2.5682 (TasmanianThylacine)
  AucStatWOWEcon, v7.2.5682.5613(/embedded)
  AucUtilAHWindowControl, v7.2.5682.5575(/embedded)
  AucUtilAppraiser, v7.2.5682.5666(/embedded)
  AucUtilAskPrice, v7.2.5682.5599(/embedded)
  AucUtilAutoMagic, v7.2.5682.5676(/embedded)
  AucUtilCompactUI, v7.2.5682.5629(/embedded)
  AucUtilEasyBuyout, v7.2.5682.5576(/embedded)
  AucUtilFixAH, v7.2.5682 (TasmanianThylacine)
  AucUtilItemSuggest, v7.2.5682.5651(/embedded)
  AucUtilPriceLevel, v7.2.5682.5633(/embedded)
  AucUtilScanButton, v7.2.5682.5631(/embedded)
  AucUtilScanFinish, v7.2.5682.5588(/embedded)
  AucUtilScanProgress, v7.2.5682.4979(/embedded)
  AucUtilScanStart, v7.2.5682.5347(/embedded)
  AucUtilSearchUI, v7.2.5682.5672(/embedded)
  AucUtilSimpleAuction, v7.2.5682.5654(/embedded)
  AucUtilVendMarkup, v7.2.5682.4828(/embedded)
  AutoRepair, v
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, vv7.1.10
  BadBoyCCleaner, vv7.1.1
  BadBoyHistory, v1.31
  BattlePetCount, v1.8.10
  BattlePetTabs, v7.0.0.160625
  BeanCounter, v7.2.5682 (TasmanianThylacine)
  BelowAverageItems, v1.23
  BindsWhen, v7.1.0.0
  CanIMogIt, v7.0.3.23
  ChatLoot, v1.6.1
  ClassicQuestLog, v1.2.7
  Comix, v6.2.3.0
  Compass, v1.0.6
  Configator, v5.1.DEV.406(/embedded)
  CritterEmote, v1.8
  DarkmoonProfessional, v7.0.3.1
  DataStore, vr60
  DataStoreAchievements, vr43
  DataStoreAgenda, vr24
  DataStoreCharacters, vr37
  DebugLib, v5.1.DEV.337(/embedded)
  DragEmAll, v1.0.6
  Dresser, v7.0.0.160625
  Elephant, v3.5.1
  Engravings, v
  ExaltedWithTheFloor, v2.
  ExecutiveAssistant, v1.0.2
  Exonumist, v7.1.0.0
  FactionAddict, v1.39
  FarmIt2, v
  FishingBuddy, v1.7.11
  FlightMapEnhanced, v2.1.3
  GarrisonMissionManager, vv49
  Gatherer, v7.0.1
  GnomishVendorShrinker, v
  GoFish, v7.0.3.0
  Grail, v083
  GrailAchievements, v011
  GrailQuestsenUS, v22810
  GrailReputations, v007
  GrailWhen, v001
  HearKitty, v1.7.4a
  HearKittySoundPacks, vVolume 2f
  IgnoreMore, v1.1.1-40300
  InFlightLoad, v7.0.002
  KeepingTabs, v1.5
  KillTrack, vv2.11.2
  LagBar, v3.6
  LibExtraTip, v5.12.DEV.416(/embedded)
  LightHeaded, vwowi:revision
  Linkerize, v009
  Livestock, v2.5.1
  LootMsgShortener, v0.71
  MasterPlan, v0.105
  MasterPlanA, vA
  MetaMap, v7.1.0.1
  MetaMapBWP, v7.1.0.0
  MetaMapFWM, v7.1.0.0
  MetaMapNBK, v7.1.0.0
  MetaMapQST, v7.1.0.0
  MetaMapTRK, v7.1.0.0
  MetaMapWKB, v7.1.0.0
  MicroMenu, v1.2.3
  MiniLoot, v7.1.0.161026
  MobKillCount, v7.1.0
  MountFarmHelper, v7.1.0
  NameplateColors, vv1.2.2
  Overachiever, v0.98
  Pawn, v2.1.5
  PetFarmHelper, v7.1.0
  PetLeash, v3.1.1
  PetTracker, v7.1.0
  PetTrackerBreeds, v
  PetTrackerConfig, v
  PetTrackerJournal, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  Postal, vv3.5.8
  QuickQuestItem, v3.0
  RangeDisplay, vv4.5.0
  RaresTip, vr10
  SanityCheck, vv1.69
  SayRandomQuote, v7.0
  SemlarPlates, v7.1.0.1
  SilverDragon, vv3.2.8
  SimpleDing, vv1.0
  SimpleGold, v5.5.0
  Skada, v1.5-13
  Skadacfi, v0.4c
  SkadaScroll, v1.5.3
  SlideBar, v7.2.5682 (TasmanianThylacine)
  SpeedyGonzales, v1.7.6
  StoreBeGone, v1.2
  Stubby, v7.2.5682 (TasmanianThylacine)
  TabardAddict, v2.34
  TargetNameplateIndicator, v1.11
  TargetRole, v1.2.8
  TheUndermineJournal, v4.7.20161101
  TinyPad, v2.1.3
  TipHelper, v5.12.DEV.405(/embedded)
  TipTop, v2.16.1
  TokenSplainer, vr04
  TomTom, vv70000-1.1.0-85bccb5
  TrackOMatic, v1.7.0
  WardrobeSort, vv0.2.2
  WhoFramedWatcherWabbit, v2.2.1
  Wholly, v060
  WowheadBagScanner, v1.11
  WoWTokenWatch, v1.0.3
  ZoneAchievementTracker, v7.1.0.0
  BlizRuntimeLib_enUS v7.1.0.70100 <none>
  (ck=105e)

**Comment by tekkub** [comment]
Engravings isn't the source of this error, it doesn't touch that protected function at all.  It is probably being blamed because it embeds CallbackHandler, which is a shared library.  If this instance of CBH is being used by another addon that is doing something inappropriate then the blame may point at Engravings incorrectly.  Unfortunately these sorts of bugs are very hard to track down, if you can make it happen consistently you will probably find that disabling Engravings will shift the blame to another addon that has embedded shared libraries in it.
